import { Component } from '@angular/core';
import { IonApp, IonRouterOutlet } from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import {
  add,
  person,
  people,
  peopleOutline,
  planet,
  planetOutline,
  sparkles,
  create,
  createOutline,
  trash,
  share,
  shareOutline,
  shareSocial,
  eye,
  eyeOff,
  ellipsisVertical,
  chevronForward,
  close,
  checkmark,
  checkmarkCircle,
  alertCircle,
  alertCircleOutline,
  informationCircle,
  informationCircleOutline,
  warningOutline,
  warning,
  star,
  flash,
  flashOutline,
  heart,
  heartOutline,
  barbell,
  barbellOutline,
  bulb,
  bulbOutline,
  pulse,
  pulseOutline,
  statsChart,
  statsChartOutline,
  trendingUp,
  download,
  cloudDownload,
  cloudOffline,
  link,
  copy,
  gameController,
  logoGoogle,
  time,
  timeOutline,
  globe,
  globeOutline,
  lockClosed,
  lockClosedOutline,
  personAdd,
  personAddOutline,
  ellipse,
  settings,
  settingsOutline,
  chatbubbles,
  chatbubblesOutline,
  send,
  sendOutline,
  refresh,
  refreshOutline,
  build,
  buildOutline,
  colorWand,
  colorWandOutline,
  image,
  imageOutline,
  book,
  bookOutline
} from 'ionicons/icons';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [IonApp, IonRouterOutlet],
  template: `
    <ion-app>
      <ion-router-outlet></ion-router-outlet>
    </ion-app>
  `
})
export class AppComponent {
  constructor() {
    addIcons({
      add,
      person,
      people,
      'people-outline': peopleOutline,
      planet,
      'planet-outline': planetOutline,
      sparkles,
      create,
      trash,
      share,
      'share-outline': shareOutline,
      'share-social': shareSocial,
      eye,
      'eye-off': eyeOff,
      'ellipsis-vertical': ellipsisVertical,
      'chevron-forward': chevronForward,
      close,
      checkmark,
      'checkmark-circle': checkmarkCircle,
      'alert-circle': alertCircle,
      'alert-circle-outline': alertCircleOutline,
      'information-circle': informationCircle,
      'information-circle-outline': informationCircleOutline,
      'warning-outline': warningOutline,
      warning,
      star,
      flash,
      'flash-outline': flashOutline,
      heart,
      'heart-outline': heartOutline,
      barbell,
      'barbell-outline': barbellOutline,
      bulb,
      'bulb-outline': bulbOutline,
      pulse,
      'pulse-outline': pulseOutline,
      'stats-chart': statsChart,
      'stats-chart-outline': statsChartOutline,
      'trending-up': trendingUp,
      download,
      'cloud-download': cloudDownload,
      'cloud-offline': cloudOffline,
      link,
      copy,
      'game-controller': gameController,
      'logo-google': logoGoogle,
      time,
      'time-outline': timeOutline,
      globe,
      'globe-outline': globeOutline,
      'lock-closed': lockClosed,
      'lock-closed-outline': lockClosedOutline,
      'person-add': personAdd,
      'person-add-outline': personAddOutline,
      ellipse,
      settings,
      'settings-outline': settingsOutline,
      'create-outline': createOutline,
      chatbubbles,
      'chatbubbles-outline': chatbubblesOutline,
      send,
      'send-outline': sendOutline,
      refresh,
      'refresh-outline': refreshOutline,
      build,
      'build-outline': buildOutline,
      'color-wand': colorWand,
      'color-wand-outline': colorWandOutline,
      image,
      'image-outline': imageOutline,
      book,
      'book-outline': bookOutline
    });
  }
}
