import { bootstrapApplication } from '@angular/platform-browser';
import { defineCustomElements } from '@ionic/core/loader';
import { addIcons } from 'ionicons';
import {
  // Stats icons
  barbellOutline,
  flashOutline,
  heartOutline,
  bulbOutline,
  eyeOutline,
  shieldOutline,
  flameOutline,
  waterOutline,
  leafOutline,
  sparklesOutline,
  cubeOutline,
  chatbubblesOutline,
  pulseOutline,
  snowOutline,
  hardwareChipOutline,
  // UI icons
  planetOutline,
  personOutline,
  peopleOutline,
  starOutline,
  infiniteOutline,
  optionsOutline,
  addOutline,
  add,
  addCircle,
  createOutline,
  trashOutline,
  trash,
  checkmark,
  checkmarkCircle,
  arrowBack,
  arrowForward,
  chevronForward,
  ellipsisVertical,
  informationCircle,
  alertCircle,
  closeCircle,
  trendingUp,
  trendingUpOutline,
  statsChart,
  trophy,
  star,
  refresh,
  create,
  book,
  heart,
  flash,
  globe,
  globeOutline,
  lockClosedOutline,
  colorWandOutline,
  shareSocial,
  apps,
  logIn,
  personCircle,
  people,
  logoGoogle,
  mail,
  lockClosed,
  eye,
  eyeOff,
  menu,
  close,
  home,
  settings,
  help,
  exit,
  planet,
  person,
  sparkles,
  // Image upload icons
  cloudUploadOutline,
  camera
} from 'ionicons/icons';

import { appConfig } from './app/app.config';
import { AppComponent } from './app/app.component';

// Register all icons used in the app
addIcons({
  // Stats icons
  'barbell-outline': barbellOutline,
  'flash-outline': flashOutline,
  'heart-outline': heartOutline,
  'bulb-outline': bulbOutline,
  'eye-outline': eyeOutline,
  'shield-outline': shieldOutline,
  'flame-outline': flameOutline,
  'water-outline': waterOutline,
  'leaf-outline': leafOutline,
  'sparkles-outline': sparklesOutline,
  'cube-outline': cubeOutline,
  'chatbubbles-outline': chatbubblesOutline,
  'pulse-outline': pulseOutline,
  'snow-outline': snowOutline,
  'hardware-chip-outline': hardwareChipOutline,
  // UI icons
  'planet-outline': planetOutline,
  'person-outline': personOutline,
  'people-outline': peopleOutline,
  'star-outline': starOutline,
  'infinite-outline': infiniteOutline,
  'options-outline': optionsOutline,
  'add-outline': addOutline,
  'add': add,
  'add-circle': addCircle,
  'create-outline': createOutline,
  'trash-outline': trashOutline,
  'checkmark': checkmark,
  'checkmark-circle': checkmarkCircle,
  'arrow-back': arrowBack,
  'arrow-forward': arrowForward,
  'chevron-forward': chevronForward,
  'ellipsis-vertical': ellipsisVertical,
  'information-circle': informationCircle,
  'alert-circle': alertCircle,
  'close-circle': closeCircle,
  'trending-up': trendingUp,
  'trending-up-outline': trendingUpOutline,
  'stats-chart': statsChart,
  'trophy': trophy,
  'star': star,
  'refresh': refresh,
  'create': create,
  'book': book,
  'heart': heart,
  'flash': flash,
  'globe': globe,
  'globe-outline': globeOutline,
  'lock-closed-outline': lockClosedOutline,
  'color-wand-outline': colorWandOutline,
  'share-social': shareSocial,
  'apps': apps,
  'log-in': logIn,
  'person-circle': personCircle,
  'people': people,
  'logo-google': logoGoogle,
  'mail': mail,
  'lock-closed': lockClosed,
  'eye': eye,
  'eye-off': eyeOff,
  'menu': menu,
  'close': close,
  'home': home,
  'settings': settings,
  'help': help,
  'exit': exit,
  'planet': planet,
  'person': person,
  'sparkles': sparkles,
  // Image upload icons
  'cloud-upload-outline': cloudUploadOutline,
  'camera': camera,
  'trash': trash
});

// Register Ionic Web Components for production builds
defineCustomElements(window);

bootstrapApplication(AppComponent, appConfig)
  .catch((err) => console.error(err));
