import { bootstrapApplication } from '@angular/platform-browser';
import { addIcons } from 'ionicons';
import {
  // Stats icons
  barbellOutline,
  flashOutline,
  heartOutline,
  bulbOutline,
  eyeOutline,
  shieldOutline,
  flameOutline,
  waterOutline,
  leafOutline,
  sparklesOutline,
  cubeOutline,
  chatbubblesOutline,
  pulseOutline,
  snowOutline,
  hardwareChipOutline,
  // UI icons
  planetOutline,
  personOutline,
  peopleOutline,
  starOutline,
  infiniteOutline,
  optionsOutline,
  addOutline,
  add,
  addCircle,
  createOutline,
  trashOutline,
  trash,
  checkmark,
  checkmarkCircle,
  arrowBack,
  arrowForward,
  arrowForwardOutline,
  chevronForward,
  chevronForwardOutline,
  ellipsisVertical,
  informationCircle,
  alertCircle,
  closeCircle,
  trendingUp,
  trendingUpOutline,
  statsChart,
  trophy,
  star,
  refresh,
  create,
  book,
  heart,
  flash,
  globe,
  globeOutline,
  lockClosedOutline,
  colorWandOutline,
  shareSocial,
  apps,
  logIn,
  personCircle,
  people,
  logoGoogle,
  mail,
  lockClosed,
  eye,
  eyeOff,
  menu,
  close,
  home,
  settings,
  help,
  exit,
  planet,
  person,
  sparkles,
  // Image upload icons
  cloudUploadOutline,
  camera,
  // Missing icons (previously not registered)
  cellularOutline,
  download,
  link,
  ribbonOutline,
  warning,
  warningOutline,
  // Additional icons from app.component.ts
  share,
  shareOutline,
  checkmarkCircleOutline,
  alertCircleOutline,
  informationCircleOutline,
  barbell,
  bulb,
  pulse,
  statsChartOutline,
  cloudDownload,
  cloudOffline,
  copy,
  gameController,
  time,
  timeOutline,
  personAdd,
  personAddOutline,
  ellipse,
  settingsOutline,
  chatbubbles,
  send,
  sendOutline,
  refreshOutline,
  build,
  buildOutline,
  colorWand,
  image,
  imageOutline,
  bookOutline,
  speedometer,
  speedometerOutline,
  personCircleOutline,
  documentText,
  documentTextOutline,
  terminal,
  terminalOutline,
  codeSlash,
  codeSlashOutline,
  server,
  serverOutline,
  shield,
  key,
  keyOutline,
  appsOutline,
  logInOutline,
  addCircleOutline,
  trophyOutline
} from 'ionicons/icons';

import { appConfig } from './app/app.config';
import { AppComponent } from './app/app.component';

// Register all icons used in the app - SINGLE SOURCE OF TRUTH
addIcons({
  // Stats icons
  'barbell-outline': barbellOutline,
  'barbell': barbell,
  'flash-outline': flashOutline,
  'heart-outline': heartOutline,
  'bulb-outline': bulbOutline,
  'bulb': bulb,
  'eye-outline': eyeOutline,
  'shield-outline': shieldOutline,
  'shield': shield,
  'flame-outline': flameOutline,
  'water-outline': waterOutline,
  'leaf-outline': leafOutline,
  'sparkles-outline': sparklesOutline,
  'cube-outline': cubeOutline,
  'chatbubbles-outline': chatbubblesOutline,
  'chatbubbles': chatbubbles,
  'pulse-outline': pulseOutline,
  'pulse': pulse,
  'snow-outline': snowOutline,
  'hardware-chip-outline': hardwareChipOutline,
  // UI icons
  'planet-outline': planetOutline,
  'planet': planet,
  'person-outline': personOutline,
  'person': person,
  'people-outline': peopleOutline,
  'people': people,
  'star-outline': starOutline,
  'star': star,
  'infinite-outline': infiniteOutline,
  'options-outline': optionsOutline,
  'add-outline': addOutline,
  'add': add,
  'add-circle': addCircle,
  'add-circle-outline': addCircleOutline,
  'create-outline': createOutline,
  'create': create,
  'trash-outline': trashOutline,
  'trash': trash,
  'checkmark': checkmark,
  'checkmark-circle': checkmarkCircle,
  'checkmark-circle-outline': checkmarkCircleOutline,
  'arrow-back': arrowBack,
  'arrow-forward': arrowForward,
  'arrow-forward-outline': arrowForwardOutline,
  'chevron-forward': chevronForward,
  'chevron-forward-outline': chevronForwardOutline,
  'ellipsis-vertical': ellipsisVertical,
  'information-circle': informationCircle,
  'information-circle-outline': informationCircleOutline,
  'alert-circle': alertCircle,
  'alert-circle-outline': alertCircleOutline,
  'close-circle': closeCircle,
  'trending-up': trendingUp,
  'trending-up-outline': trendingUpOutline,
  'stats-chart': statsChart,
  'stats-chart-outline': statsChartOutline,
  'trophy': trophy,
  'trophy-outline': trophyOutline,
  'refresh': refresh,
  'refresh-outline': refreshOutline,
  'book': book,
  'book-outline': bookOutline,
  'heart': heart,
  'flash': flash,
  'globe': globe,
  'globe-outline': globeOutline,
  'lock-closed-outline': lockClosedOutline,
  'lock-closed': lockClosed,
  'color-wand-outline': colorWandOutline,
  'color-wand': colorWand,
  'share-social': shareSocial,
  'share': share,
  'share-outline': shareOutline,
  'apps': apps,
  'apps-outline': appsOutline,
  'log-in': logIn,
  'log-in-outline': logInOutline,
  'person-circle': personCircle,
  'person-circle-outline': personCircleOutline,
  'logo-google': logoGoogle,
  'mail': mail,
  'eye': eye,
  'eye-off': eyeOff,
  'menu': menu,
  'close': close,
  'home': home,
  'settings': settings,
  'settings-outline': settingsOutline,
  'help': help,
  'exit': exit,
  'sparkles': sparkles,
  // Image upload icons
  'cloud-upload-outline': cloudUploadOutline,
  'camera': camera,
  // Previously missing icons - NOW REGISTERED
  'cellular-outline': cellularOutline,
  'download': download,
  'link': link,
  'ribbon-outline': ribbonOutline,
  'warning': warning,
  'warning-outline': warningOutline,
  // Additional icons consolidated from app.component.ts
  'cloud-download': cloudDownload,
  'cloud-offline': cloudOffline,
  'copy': copy,
  'game-controller': gameController,
  'time': time,
  'time-outline': timeOutline,
  'person-add': personAdd,
  'person-add-outline': personAddOutline,
  'ellipse': ellipse,
  'send': send,
  'send-outline': sendOutline,
  'build': build,
  'build-outline': buildOutline,
  'image': image,
  'image-outline': imageOutline,
  'speedometer': speedometer,
  'speedometer-outline': speedometerOutline,
  'document-text': documentText,
  'document-text-outline': documentTextOutline,
  'terminal': terminal,
  'terminal-outline': terminalOutline,
  'code-slash': codeSlash,
  'code-slash-outline': codeSlashOutline,
  'server': server,
  'server-outline': serverOutline,
  'key': key,
  'key-outline': keyOutline
});

bootstrapApplication(AppComponent, appConfig)
  .catch((err) => console.error(err));
